version: '3'
services:
  mysql:
    image: mysql:8 #使用的镜像
    container_name: soj-mysql #容器名称
    environment:
      MYSQL_ROOT_PASSWORD: atteity890560 #root密码
    ports:
      - "3306:3306" #端口映射
    volumes:
      - ./.mysql-data:/var/lib/mysql #数据卷映射
      - ./mysql-init:/docker-entrypoint-initdb.d #启动脚本
    restart: always #重启策略
    networks:
      - soj-network #网络

  redis:
    image: redis:6
    container_name: soj-redis
    ports:
      - "6379:6379"
    networks:
      - soj-network
    volumes:
      - ./.redis-data:/data #持久化数据

  rabbitmq:
    image: rabbitmq:3.12.6-management #支持web管理界面
    container_name: soj-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: shiro #用户名
      RABBITMQ_DEFAULT_PASS: atteity890560 #密码
    ports:
      - "5672:5672" #端口映射
      - "15672:15672" #面板端口映射
    volumes:
      - ./.rabbitmq-data:/var/lib/rabbitmq #持久化数据
    networks:
      - soj-network

  nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: soj-nacos
    ports:
      - "8848:8848"
    volumes:
      - ./.nacos-data:/home/nacos/data #持久化数据
    networks:
      - soj-network
    environment:
      - MODE=standalone #单机模式
      - PREFER_HOST_MODE=hostname #主机名模式
      - TZ=Asia/Shanghai #时区

networks:
  soj-network:
    driver: bridge